<a href="https://colab.research.google.com/github/DionKimmm/2019SummerML/blob/master/Day07_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![numpy logo](http://drive.google.com/uc?export=view&id=1As8PTCtVHZb8wTPm6hxHcBAG4FCqjNxO)



### *   NumPy는 파이썬을 이용하여 과학계산을 할때 사용하는 기본적인 패키지
### * 다차원 배열과 행렬 객체가 포함
### * 배열(행렬) 객체를 처리하는 고급 함수들이 있어서, 반복문이 불필요
### * 유용한 선형대수 풀이, 푸리에 변환, 난수 계산기 등의 다양한 기능
### *   머신러닝에 필수적인 큰 수치 데이터를 다루게 되는데 이러한 수치 데이터 처리에 적합한 패키지
### * 행렬 계산의 사실상 표준 패키지
### * 빠른 연산이 필요한 경우 적합
### * 고급 선형대수학 라이브러리를 제공

![대체 텍스트](http://drive.google.com/uc?export=view&id=1cmHjBhz9nfXvwU3aE_S63COPV-oCfsH2)
![대체 텍스트](http://drive.google.com/uc?export=view&id=13CI7_9UsMWYn6KGDm4ihowwbXvLCQWC5)
![대체 텍스트](http://drive.google.com/uc?export=view&id=10CXHgg5yEQxuH6R_xXWbNFMpoj8RtfaC)




<div>NumPy는 수치해석을 위한 라이브러리인만큼 숫자형 자료형에 대해서는&nbsp;<a href="https://kongdols-room.tistory.com/23" target="_blank" class="tx-link">파이썬</a><a href="https://kongdols-room.tistory.com/23" target="_blank" class="tx-link">&nbsp;내장 숫자자료형</a>에 비해&nbsp;다양한 자료형들이 존재한다.</div><p><br /></p><p><b><span style="font-size: 12pt;">NumPy에서의 자료형</span></b></p><p><br /></p><p>NumPy에서는 제공하는 숫자형 자료형의 종류는&nbsp;정수(int), 부호없는 정수(uint), 실수(float), 복소수(complex), 논리(bool)로 총 5가지로&nbsp;나뉜다.</p><p>자료형뒤에 숫자는 일반적으로 bit수(memory)를 의미한다.</p><p>아래에 설명하는 데이터 타입들은 전부 자료형 정의 및 변경을 위한 함수로써 사용이 가능하다.</p><p><br /></p><p><b>정수형 자료형</b></p><p>&nbsp;&nbsp;○ NumPy에서 제공하는 정수형 자료형은 크게 2가지로 나뉜다.</p><p>&nbsp; &nbsp;&nbsp;▷ int는 음수와 양수를 다 아우르는 정수형 자료형이다.</p><p>&nbsp; &nbsp; ▷ uint는 0을 포함한 양수를 혹은 부호없는 정수를&nbsp;제공하는 자료형이다.</p><p>&nbsp; ○&nbsp;NumPy에서 사용하는 정수형 자료형에 대한 설명이 다음 표와 같이 제시되어 있다.</p><div>&nbsp; &nbsp;&nbsp;▷ 기본적으로 int나 uint 뒤에 오는 숫자는 bit의 개수를 의미한다. (bit는 0과 1만 존재하는 컴퓨터에서 가장 작은 단위의 자료형이다.)</div><div>&nbsp; &nbsp; ▷ 예를들어, 뒤에 숫자가 8이면 2^8개 만큼의 정수를 표현하는 것이 가능하다.</div><p style="text-align: left;"><br /></p><table class="txc-table" width="528" cellspacing="0" cellpadding="0" border="0" style="border: none; border-collapse: collapse; width: 528px;" 맑은="" 고딕",="" sans-serif;font-size:13px"=""><tbody><tr><td style="width: 143px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p style="text-align: center;"><b>데이터 타입</b></p></td>
<td style="width: 384px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(204, 204, 204);"><p style="text-align: center;"><b>설명</b></p></td>
</tr>
<tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">int_</p></td>
<td style="width: 384px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 정수형 자료형 기본값</p><p style="text-align: left;">&nbsp; - C언어에서 long과 같다.</p><p style="text-align: left;">&nbsp; - 일반적으로 int64나 int32이다.</p></td>
</tr>
<tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;intc</p></td>
<td style="width: 384px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - C언어 int와 동일하다.</p><p style="text-align: left;">&nbsp; - 일반적으로 int32와 int64이다.</p></td>
</tr>
<tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;intp</p></td>
<td style="width: 384px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 인덱싱에 사용되는 정수형이다.</p><p style="text-align: left;">&nbsp; - C언어에서&nbsp; ssize_t와 동일하다.</p><p style="text-align: left;">&nbsp; - 일반적으로 int32나 int64이다.</p></td>
</tr>
<tr><td style="width: 143px; height: 52px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;int8</p></td>
<td style="width: 384px; height: 52px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 1바이트 만큼의 정수 표현이 가능하다.</p><p style="text-align: left;">&nbsp; - 즉, 2^8 개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; - -128 ~ 127</p></td>
</tr>
<tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;int16</p></td>
<td style="width: 384px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 2^16개수 만큼&nbsp;표현이 가능하다.</p><p style="text-align: left;">&nbsp; - -32,768 ~&nbsp;32,767</p></td>
</tr>
<tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;int32</p></td>
<td style="width: 384px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 2^32개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; -&nbsp;-2,147,483,648 ~&nbsp;2,147,483,647</p></td>
</tr>

<tr><td style="width: 143px; height: 52px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;uint8</p></td>
<td style="width: 384px; height: 52px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 양수만 표현이 가능하다.</p><p style="text-align: left;">&nbsp; - 2^8개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; -&nbsp;0 ~&nbsp;255</p></td>
</tr>
<tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;uint16</p></td>
<td style="width: 384px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; -&nbsp;2^16개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; - 0 ~&nbsp;65,535</p></td>
</tr>
<tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);" rowspan="1"><p style="text-align: center;">&nbsp;uint32</p></td><td style="width: 384px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);" rowspan="1"><p style="text-align: left;">&nbsp; - 2^32개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; -&nbsp;0 ~&nbsp;4,294,967,295</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);" rowspan="1"><p style="text-align: center;">&nbsp;uint64</p></td><td style="width: 384px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);" rowspan="1"><p style="text-align: left;">&nbsp; -&nbsp;2^64개수 만큼 표현이 가능하다.</p><p style="text-align: left;">&nbsp; -&nbsp;0 ~&nbsp;18,446,744,073,709,551,615</p></td></tr></tbody></table><p style="text-align: center;"></p><p><br /></p><p><br /></p><p><b>실수형 자료형</b></p><p>&nbsp;&nbsp;○ 아래&nbsp;표는 NumPy에서&nbsp;실수형 자료형을 보여준다.</p><p>&nbsp; &nbsp;&nbsp;▷ 자료형 뒤에 숫자는 정수와 마찬가지로 bit수를 의미한다.</p><p><br /></p><table class="txc-table" width="531" cellspacing="0" cellpadding="0" border="0" 맑은="" 고딕",="" sans-serif;font-size:13px"="" style="border: none; border-collapse: collapse; width: 531px;"><tbody><tr><td style="width: 143px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;데이터 타입</p></td><td style="width: 387px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;설명</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">float_</p></td><td style="width: 387px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - float64의 약칭이다.</p></td></tr><tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;float16</p></td><td style="width: 387px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp;&nbsp;- 반정밀도(Half precision)를 가지는 실수형 자료형이다.</p><p>&nbsp; - 5 bit의 지수와, 10 bit의 소수로 구성된다.</p></td></tr><tr><td style="width: 143px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;float32</p></td><td style="width: 387px; height: 35px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - 단정밀도(Single precision)를 가지는 실수형 자료형이다.</p><p>&nbsp; - 8&nbsp;bit의 지수와, 23&nbsp;bit의 소수로 구성된다.</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;float64</p></td><td style="width: 387px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - 배정밀도(Double&nbsp;precision)를 가지는 실수형 자료형이다.</p><p>&nbsp; - 11&nbsp;bit의 지수와, 52&nbsp;bit의 소수로 구성된다.</p></td></tr></tbody></table><p><br /></p><p><br /></p><p><b>복소수형 자료형</b></p><p>&nbsp; ○ 다음 표는 복소수형 자료형을 보여주며 숫자의 의미는 정수,&nbsp;실수와 같다.</p><p><br /></p><table class="txc-table" width="532" cellspacing="0" cellpadding="0" border="0" 맑은="" 고딕",="" sans-serif;font-size:13px"="" style="border: none; border-collapse: collapse; width: 532px;"><tbody><tr><td style="width: 143px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;데이터 타입</p></td><td style="width: 388px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;설명</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">complex_</p></td><td style="width: 388px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - complex128의 약칭이다.</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">complex64</p></td><td style="width: 388px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - 실수부분과 허수부분에 각각 floalt32의 자료형을 가진다.</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;complex128</p></td><td style="width: 388px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; -&nbsp;실수부분과 허수부분에 각각 floalt64의 자료형을 가진다.</p></td></tr></tbody></table><p><br /></p><p><br /></p><p><b>논리형 자료형</b></p><p>&nbsp; ○ NumPy는 논리형 자료형도 취급하며 다음 표에 설명되어 있다.</p><p><br /></p><table class="txc-table" width="531" cellspacing="0" cellpadding="0" border="0" 맑은="" 고딕",="" sans-serif;font-size:13px"="" style="border: none; border-collapse: collapse; width: 531px;"><tbody><tr><td style="width: 143px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;데이터 타입</p></td><td style="width: 387px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;설명</p></td></tr><tr><td style="width: 143px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">bool_ 혹은 bool</p></td><td style="width: 387px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p>&nbsp; - 하나의 바이트로 거짓(False)과 참(True)을 표현한&nbsp;자료형이다.</p></td></tr></tbody></table><p><br /></p><p><br /></p><p><b><span style="font-size: 12pt;">NumPy&nbsp;자료형과 관련된 함수/메서드</span></b></p><p>&nbsp; ○ 위에 설명한 자료형과 관련된 함수 말고도 자료형을 확인하거나 변경시킬 수 있는 함수가 존재한다.</p><p><br /></p><table class="txc-table" width="799" cellspacing="0" cellpadding="0" border="0" style="border: none; border-collapse: collapse; width: 799px;" 맑은="" 고딕",="" sans-serif;font-size:13px"=""><tbody><tr><td style="width: 141px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);"><p style="text-align: center;">함수&nbsp;</p></td><td style="width: 218px; height: 24px; border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204);" colspan="1"><p style="text-align: center;">&nbsp;사용 예</p></td>
<td style="width: 439px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-top: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">설명</p></td>
</tr>
<tr><td style="width: 141px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;dtype</p></td><td style="width: 218px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);" colspan="1"><p style="text-align: center;">x.dtype&nbsp;</p></td>
<td style="width: 439px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 변수 x의 자료형을 출력한다.</p></td>
</tr>
<tr><td style="width: 141px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">&nbsp;astype()</p></td><td style="width: 218px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);" colspan="1"><p style="text-align: center;">x.astype(<i>dtype</i>)</p></td>
<td style="width: 439px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 변수 x를 <i>dtype</i>의 자료형으로 변경하여 출력한다.</p></td>
</tr>
<tr><td style="width: 141px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);"><p style="text-align: center;">issubtype( , )&nbsp;</p></td><td style="width: 218px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204); border-left: 1px solid rgb(204, 204, 204);" colspan="1"><p style="text-align: center;">np.issubdtype(<i>dtype, upperdtype</i>)&nbsp;</p></td>
<td style="width: 439px; height: 24px; border-bottom: 1px solid rgb(204, 204, 204); border-right: 1px solid rgb(204, 204, 204);"><p style="text-align: left;">&nbsp; - 자료형 <i>dtype</i>이&nbsp;<i>upperdatatype</i>의 하위자료형이면&nbsp;참(True)을&nbsp;아니면 거짓(False)를 출력한다.&nbsp;</p></td>
</tr>

</tbody></table>

In [0]:
import numpy as np

In [0]:
i = np.int64(5)
print(i, type(i), i.dtype)

i1 = np.int64(0)
print(i1, type(i1), i1.dtype)

5 <class 'numpy.int64'> int64
0 <class 'numpy.int64'> int64


In [0]:
f = np.float64()
print(f, f.dtype)

f1 = np.float64(5)
print(f1, type(f1))

0.0 float64
5.0 <class 'numpy.float64'>


## ndarray

* 파이썬의 numpy 패키지에는 ndarray라는 다차원 배열 클래스가 있다
* 동일한 형의 자료값을 저장
* 동일한 차원의 배열에 대해서 덧셈, 뺄셈이 가능함
* 리스트 연산에 비해 연산 속도가 빠르다
* 인덱싱, 크기 구하기 연산이 가능하며, shape, 아이템의 크기, 차원, 아이템 바이트 등의 속성이 있다


In [0]:
list1 = [1.3, 2., 3, 4, 5]
arr = np.array(list1)
print(arr, type(arr), arr.dtype)

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'> float64


In [0]:
list2 = [[1,2],[3,4]]
print(list2)
arr1 = np.array(list2)
print(arr1, type(arr1), arr1.dtype)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64


## 배열의 연산

![대체 텍스트](http://drive.google.com/uc?export=view&id=1yFoUH7Io8hRKdQW4i-L02oyT1lazIfhW)

In [0]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[10, 20], [30, 40]])
print(b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


* shape: shape 속성은 배열의 차원 정보를 가지고 있다
* 예를들어 (3, 4)라는 shape 이 있다면 3행 4열의 2차원 배열을 의미함
* ndim: 배열의 축(차원)의 개수를 포함하고 있음
* dtype: 배열 원소 객체의 자료형을 기술함
* itemsize: 배열 원소 객체의 크기를 바이트 단위로 표시함, float64라는 자료형은 8바이트이므로 itemsize는 8이 된다
* size: 배열 원소의 개수인데 shape (3, 4)일 경우 3 * 4 = 12개임

In [0]:
a.ndim

2

In [0]:
a.shape

(2, 2)

In [0]:
b = np.array([1,2,3,4])
print(b.ndim, b.shape)
print((4))

1 (4,)
4



##### 덧셈

![대체 텍스트](http://drive.google.com/uc?export=view&id=1Y9BH1jf2R5EQr9JkkM9KvxywjF3XTiL1)

In [0]:
c = a + b
print(c)

[[11 22]
 [33 44]]


#### 뺄셈 

![대체 텍스트](http://drive.google.com/uc?export=view&id=1K-k7_D9eZHri6QAQ2qVnpDtUo1iUhFzz)

In [0]:
d = b - a
print(d)

[[ 9 18]
 [27 36]]


#### 곱셈

![대체 텍스트](http://drive.google.com/uc?export=view&id=1I698Y0exq06sxhSTrk5yHpM57WP11Q8D)

In [0]:
e = a * b
print(e)

[[ 10  40]
 [ 90 160]]


#### 행렬곱

![대체 텍스트](http://drive.google.com/uc?export=view&id=1Fl_Ob3oVlEBBlgtvxGJA9Dx0tkxWZQCX)

In [0]:
b = np.array([[10,20],[30,40]])

In [0]:
f = np.matmul(a, b)
print(f)

f = a @ b
print(f)

[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]]


In [0]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
b1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(b1)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [0]:
a1@b1


array([[300, 360, 420],
       [660, 810, 960]])

## 배열 생성 관련 함수



* zeros((n, m)) 함수: n x m 배열(행렬)을 생성하며 초기값은 0으로 한다.

![대체 텍스트](http://drive.google.com/uc?export=view&id=1OLVkq7HpUaLqQO3QpNoPckG4bO3L9Gga)

In [0]:
a = np.zeros((2, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


* ones((n, m)) 함수: n x m 배열(행렬)을 생성하며 초기값은 1로 한다.

![대체 텍스트](http://drive.google.com/uc?export=view&id=1mA3bkLrNQ4pnMfrVS6YsEhimpcPl9g_M)

In [0]:
b = np.ones((2, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


* full((n, m),x) 함수: n x m 배열(행렬)을 생성하며 초기값은 x로 한다.

![대체 텍스트](http://drive.google.com/uc?export=view&id=1WNZ0U1-AzsHu4NsufafLWsHFL0XApTz0)

In [0]:
c = np.full((2, 3), 100)
print(c)

[[100 100 100]
 [100 100 100]]


* eye(n) 함수: n x n 크기의 단위행렬(Identity Matrix)을 생성한다.

![대체 텍스트](http://drive.google.com/uc?export=view&id=1xtUyn0it-wmEAJiqT4hkHmdAv0uQdBZg)

In [0]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


random.random((n, m)) 함수: n x m 배열(행렬)을 생성하며 초기값은 임의의 난수 값으로 한다

![대체 텍스트](http://drive.google.com/uc?export=view&id=1t4wIbXFpx0ZU3ejU0IJLePIinBTbuAKE)

In [0]:
e = np.random.random((3,4))
print(e)

[[0.44899164 0.6393012  0.07529802 0.58296643]
 [0.93037114 0.35437491 0.27044275 0.04172   ]
 [0.31413158 0.09334704 0.89464562 0.48166649]]


## 숫자의 열을 생성하는 함수

* arange(m,n) 함수: m에서 n-1까지 연속적인 정수나 실수를 생성함


In [0]:
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


* arange(m,n,step) 함수: m에서 n-1까지 step만큼 건너뛰며 연속적인 정수나 실수를 생성함


In [0]:
b = np.arange(0, 10, 2)
print(b)
c = np.arange(0, 1.0, 0.2)
print(c)

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8]


arange().reshape(m,n) 함수: arange() 함수가 만든 연속적인 값을 m x n 형태의 행렬로 재구성함

In [0]:
np.arange(0, 10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
np.arange(0, 10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [0]:
arr = np.arange(0, 24).reshape(4,3,2)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
3
(4, 3, 2)


## Broadcasting


![대체 텍스트](http://drive.google.com/uc?export=view&id=1DwNUKP37i9zIrvR-BX535SzqkCzWURdA)

In [0]:
arr1 = np.arange(3)
print(arr1)
arr2 = arr1+5
print(arr2)

[0 1 2]
[5 6 7]


In [0]:
arr1 = np.ones((3,3))
print(arr1)
arr2 = np.arange(3)
print(arr2)
print(arr1+arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [0]:
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3)
print(arr1+arr2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 배열의 인덱스

* numpy 배열에서 원소를 참조하기 위해서는 원소의 위치를 알아야 한다
* 이를 위해서는 인덱스를 사용한다
* 1차원 배열의 경우 인덱스 값이 파이썬 리스트의 인덱스 값과 동일하다
  * 인덱스를 사용하기 위해서는 배열이름[x]와 같이 대괄호를 사용
* 2차원 배열과 3차원 배열의 경우 인덱스를 각각 2개, 3개 사용하여 개별 원소를 참조할 수 있다 


---



* 1차원 배열

In [0]:
a = np.arange(0,4)
print(a)
print(a[1])
print(a[3])

[0 1 2 3]
1
3


* 2차원 배열

In [0]:
b = np.arange(0, 6).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [0]:
print(b[0, 0])
print(b[1, 1])
print(b[2, 0])
print(b[1])

0
3
4
[2 3]


* 3차원 배열

In [0]:
c = np.arange(0, 24).reshape(4,3,2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [0]:
print(c[0])
print()
print(c[0, 1])
print()
print(c[1])
print()
print(c[3,2])

[[0 1]
 [2 3]
 [4 5]]

[2 3]

[[ 6  7]
 [ 8  9]
 [10 11]]

[22 23]
<class 'numpy.ndarray'>


In [0]:
print(c[0,0,0])
print(c[0,1,1])
print(c[1,1,1])
print(c[2,1,1])
print(c[3,1,0])

0
3
9
15
20


## ndarray의 형변환

In [0]:
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)

[1 2 3 4 5] int64


In [0]:
f_arr = arr.astype(np.float64)
print(f_arr, f_arr.dtype)

[1. 2. 3. 4. 5.] float64


# 난수발생


### random.randint(n1, n2)
* 주어진 숫자사이의 균일 분포의 난수 1개 생성
* n1을 생략하면 0
* n2 포함되지 않음


In [0]:
np.random.randint(5)

np.random.randint(7)

0

In [0]:
np.random.randint(3,10)

5

### np.random.rand(m, n)
* 0~1 사이의 균일분포의  난수로 구성된 array 생성


In [0]:
np.random.rand(5)

array([0.72555112, 0.17350868, 0.36547557, 0.18921254, 0.3012673 ])

In [0]:
np.random.rand(3,4)

array([[0.44675765, 0.15456547, 0.66313713, 0.27745846],
       [0.38037648, 0.27121051, 0.16786421, 0.0480652 ],
       [0.64356117, 0.49157225, 0.13641183, 0.28940589]])

### np.random.randn(m, n)
* 평균 0, 표준편차 1의 가우시안 표준정규분포의 난수로 구성된 array 생성

In [0]:
np.random.randn(5)

array([ 1.34098678,  0.91486347,  0.1751477 , -0.46060273, -0.28662309])

In [0]:
np.random.randn(3,2)

array([[-1.04476131,  1.00358122],
       [-1.25777289,  0.54288373],
       [ 0.13264682, -0.29130549]])

### np.random.shuffle
* 데이터의 순서를 무작위로 바꿈

In [0]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 7 1 9 2 4 8 5 6 0]


In [0]:
arr1 = np.arange(0, 24).reshape(4, 6)
print(arr1)
np.random.shuffle(arr1)
print(arr1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [0]:
arr2 = np.arange(0, 24).reshape(4,3,2)
print(arr2)
np.random.shuffle(arr2)
print(arr2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 6  7]
  [ 8  9]
  [10 11]]

 [[18 19]
  [20 21]
  [22 23]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[12 13]
  [14 15]
  [16 17]]]
