<a href="https://colab.research.google.com/github/DionKimmm/2019SummerML/blob/master/Day23_01_RNN_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![대체 텍스트](http://drive.google.com/uc?export=view&id=1-yNJvsVyZCFvOONiyv0Ra0GKqzHs-PwS)

In [0]:
import warnings
warnings.filterwarnings(action='ignore') 

In [0]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # reproducibility


In [0]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

In [0]:
h = [1,0,0,0,0]
i = [0,1,0,0,0]
e = [0,0,1,0,0]
l = [0,0,0,1,0]
o = [0,0,0,0,1]

x_data = np.array([[h,i,h,e,l,l]], dtype=np.float32)

# x_data = np.array([[h,e,l,l,o],
#                    [e,o,l,l,l],
#                    [l,l,e,e,l]], dtype=np.float32)
print(x_data)
print(x_data.shape)

[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)


* x_data.shape >> (시퀀스 데이터의 개수, 시퀀스의 길이, 원핫 요소의 개수)입니다.

In [0]:
hidden_size = 5
sequence_length = 6
cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)

In [0]:

# x_data = np.array([[[1,0,0,0]]], dtype = np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
print(outputs)

Tensor("rnn/transpose_1:0", shape=(1, 6, 5), dtype=float32)


In [0]:

sess.run(tf.global_variables_initializer())
print(outputs.eval())

[[[-0.54487395  0.51879334 -0.13921815 -0.27288058 -0.10411536]
  [ 0.32000193 -0.4719932  -0.5871584  -0.44938266 -0.42658788]
  [-0.6841308   0.10090849 -0.283207    0.04200775 -0.05635734]
  [-0.3914819  -0.05141543 -0.40481237  0.24005753 -0.07192027]
  [-0.30995372 -0.37773475  0.01134454  0.22347264 -0.06164647]
  [-0.15240254 -0.1087274   0.29754725  0.17276976 -0.38839933]]]
